server:
  port: 8761            # Eureka Server 기본 포트, 클라이언트들이 이 주소로 접속함

spring:
  application:
    name: service-discovery  # 서비스 이름, Eureka 대시보드에 표시됨

eureka:
  client:
    register-with-eureka: false  # Eureka Server는 스스로를 등록하지 않음
    fetch-registry: false        # 클라이언트 서비스 목록을 가져오지 않음 (서버라 필요 없음)