server:
  port: 8761  # ??? ?? ??? 8761? ?? (?? Eureka Server? ?? ??)

spring:
  application:
    # ???????? ??? ??
    name: service-discovery
eureka:
  client: # ???? true???, Eureka Server??? ????? false? ???? ?
    register-with-eureka: false  # ??(Eureka Server)? Eureka? ???? ??
    fetch-registry: false        # ?? Eureka ????? ???? ??? ???? ?? (Eureka Server ????? ?? ??)